/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_PhysicalBoundaryCalc */

#ifndef _Included_rpnumerics_PhysicalBoundaryCalc
#define _Included_rpnumerics_PhysicalBoundaryCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_PhysicalBoundaryCalc
 * Method:    calcNative
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_PhysicalBoundaryCalc_calcNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
