/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_EnvelopeCurveCalc */

#ifndef _Included_rpnumerics_EnvelopeCurveCalc
#define _Included_rpnumerics_EnvelopeCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_EnvelopeCurveCalc
 * Method:    nativeCalc
 * Signature: (II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_EnvelopeCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
