/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_RarefactionOrbitCalc */

#ifndef _Included_rpnumerics_RarefactionOrbitCalc
#define _Included_rpnumerics_RarefactionOrbitCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_RarefactionOrbitCalc
 * Method:    calc
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lrpnumerics/PhasePoint;II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_RarefactionOrbitCalc_calc
  (JNIEnv *, jobject, jstring, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
