/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_BuckleyLeverettinInflectionCurveCalc */

#ifndef _Included_rpnumerics_BuckleyLeverettinInflectionCurveCalc
#define _Included_rpnumerics_BuckleyLeverettinInflectionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_BuckleyLeverettinInflectionCurveCalc
 * Method:    nativeCalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_BuckleyLeverettinInflectionCurveCalc_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
