/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_plugin_RPnPluginManager */

#ifndef _Included_rpnumerics_plugin_RPnPluginManager
#define _Included_rpnumerics_plugin_RPnPluginManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_plugin_RPnPluginManager
 * Method:    setPluginDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rpnumerics_plugin_RPnPluginManager_setPluginDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     rpnumerics_plugin_RPnPluginManager
 * Method:    addClass
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rpnumerics_plugin_RPnPluginManager_addClass
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
