/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_ManifoldOrbitCalc */

#ifndef _Included_rpnumerics_ManifoldOrbitCalc
#define _Included_rpnumerics_ManifoldOrbitCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_ManifoldOrbitCalc
 * Method:    recalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ManifoldOrbitCalc_recalc
  (JNIEnv *, jobject);

/*
 * Class:     rpnumerics_ManifoldOrbitCalc
 * Method:    calc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ManifoldOrbitCalc_calc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
