/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_OrbitCalc */

#ifndef _Included_rpnumerics_OrbitCalc
#define _Included_rpnumerics_OrbitCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_OrbitCalc
 * Method:    recalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_OrbitCalc_recalc
  (JNIEnv *, jobject);

/*
 * Class:     rpnumerics_OrbitCalc
 * Method:    calc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_OrbitCalc_calc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
