/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_ShockCurveCalc */

#ifndef _Included_rpnumerics_ShockCurveCalc
#define _Included_rpnumerics_ShockCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_ShockCurveCalc
 * Method:    calc
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lrpnumerics/PhasePoint;II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ShockCurveCalc_calc
  (JNIEnv *, jobject, jstring, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
