/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_RPNUMERICS */

#ifndef _Included_rpnumerics_RPNUMERICS
#define _Included_rpnumerics_RPNUMERICS
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: INCREASING_LAMBDA */
/* Inaccessible static: odeSolver_ */
/* Inaccessible static: profile_ */
/* Inaccessible static: hugoniotCurveCalc_ */
#ifdef __cplusplus
}
#endif
#endif
