/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_HugoniotCurveCalcND */

#ifndef _Included_rpnumerics_HugoniotCurveCalcND
#define _Included_rpnumerics_HugoniotCurveCalcND
#ifdef __cplusplus
extern "C" {
#endif
#undef rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT
#define rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT 0.01
/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    calc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotCurveCalcND_calc
  (JNIEnv *, jobject);

/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    recalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotCurveCalcND_recalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
