/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_NativeFluxFunction */

#ifndef _Included_rpnumerics_NativeFluxFunction
#define _Included_rpnumerics_NativeFluxFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_NativeFluxFunction
 * Method:    nativeJet
 * Signature: (Lrpnumerics/WaveState;Lwave/util/JetMatrix;I)I
 */
JNIEXPORT jint JNICALL Java_rpnumerics_NativeFluxFunction_nativeJet
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     rpnumerics_NativeFluxFunction
 * Method:    nativeVectorJet
 * Signature: (Lwave/util/RealVector;Lwave/util/JetMatrix;I)I
 */
JNIEXPORT jint JNICALL Java_rpnumerics_NativeFluxFunction_nativeVectorJet
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
