/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_FluxFunction */

#ifndef _Included_rpnumerics_FluxFunction
#define _Included_rpnumerics_FluxFunction
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: DEFAULT_A */
/* Inaccessible static: DEFAULT_B */
/* Inaccessible static: DEFAULT_C */
/*
 * Class:     rpnumerics_FluxFunction
 * Method:    nativeJet
 * Signature: (Lrpnumerics/WaveState;Lwave/util/JetMatrix;I)I
 */
JNIEXPORT jint JNICALL Java_rpnumerics_FluxFunction_nativeJet
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     rpnumerics_FluxFunction
 * Method:    nativeVectorJet
 * Signature: (Lwave/util/RealVector;Lwave/util/JetMatrix;I)I
 */
JNIEXPORT jint JNICALL Java_rpnumerics_FluxFunction_nativeVectorJet
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
