#!/bin/bash

basedir=~daniel/oficina/rpn/branches/rpn/bin

if [ $# -lt 1 ]; then
	echo "Usage: template <classname>"
	exit
fi

sed -e "s/ClassName/$1/g" $basedir/Template.h > $1".h"
sed -e "s/ClassName/$1/g" $basedir/Template.cc > $1".cc"

