/*
 * RPnCurveConfigPanel.java
 *
 * Created on January 23, 2008, 11:51 AM
 */

package rpn;

/**
 *
 * @author  edsonlan
 */
public class RPnCurveConfigPanel extends javax.swing.JPanel {
    
    /** Creates new form RPnCurveConfigPanel */
    public RPnCurveConfigPanel() {
        initComponents();
        addMethodNames();
        addFlowNames();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        methodLabel = new javax.swing.JLabel();
        flowLabel = new javax.swing.JLabel();
        familyIndexLabel = new javax.swing.JLabel();
        methodComboBox = new javax.swing.JComboBox();
        flowComboBox = new javax.swing.JComboBox();
        familyIndexComboBox = new javax.swing.JComboBox();

        methodLabel.setText("Method");

        flowLabel.setText("Flow");

        familyIndexLabel.setText("Family Index");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(methodLabel)
                    .add(methodComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(flowLabel)
                    .add(flowComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(familyIndexLabel)
                    .add(familyIndexComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(flowLabel)
                    .add(methodLabel)
                    .add(familyIndexLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(methodComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flowComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(familyIndexComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox familyIndexComboBox;
    private javax.swing.JLabel familyIndexLabel;
    private javax.swing.JComboBox flowComboBox;
    private javax.swing.JLabel flowLabel;
    private javax.swing.JComboBox methodComboBox;
    private javax.swing.JLabel methodLabel;
    // End of variables declaration//GEN-END:variables
    
    private void addMethodNames(){
        
        methodComboBox.addItem("ContinuationRarefactionMethod");
        methodComboBox.addItem("AnhotherRarefactionMethod");
        
        
        
    }
    private void addFlowNames(){
        
        flowComboBox.addItem("RarefactionFlow");
        flowComboBox.addItem("ShockFlow");
        
        
    }
    
    
    
}
