/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_StationaryPointCalc */

#ifndef _Included_rpnumerics_StationaryPointCalc
#define _Included_rpnumerics_StationaryPointCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_StationaryPointCalc
 * Method:    calc
 * Signature: (Lrpnumerics/PhasePoint;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_StationaryPointCalc_calc
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
