/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_HugoniotCurveCalcND */

#ifndef _Included_rpnumerics_HugoniotCurveCalcND
#define _Included_rpnumerics_HugoniotCurveCalcND
#ifdef __cplusplus
extern "C" {
#endif
#undef rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT
#define rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT 0.01
/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    setUMinus
 * Signature: (Lrpnumerics/PhasePoint;)V
 */
JNIEXPORT void JNICALL Java_rpnumerics_HugoniotCurveCalcND_setUMinus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    calc
 * Signature: (Lwave/util/RealVector;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotCurveCalcND_calc
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
