/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpn_RPnDesktopPlotter */

#ifndef _Included_rpn_RPnDesktopPlotter
#define _Included_rpn_RPnDesktopPlotter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpn_RPnDesktopPlotter
 * Method:    libraryCleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rpn_RPnDesktopPlotter_libraryCleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
