/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_InflectionCurveCalc */

#ifndef _Included_rpnumerics_InflectionCurveCalc
#define _Included_rpnumerics_InflectionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_InflectionCurveCalc
 * Method:    nativeCalc
 * Signature: (I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_InflectionCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
