/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_DiscriminantPointLevelCalc */

#ifndef _Included_rpnumerics_DiscriminantPointLevelCalc
#define _Included_rpnumerics_DiscriminantPointLevelCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_DiscriminantPointLevelCalc
 * Method:    calcNative
 * Signature: (Lwave/util/RealVector;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_DiscriminantPointLevelCalc_calcNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
