/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_CoincidenceCurveCalc */

#ifndef _Included_rpnumerics_CoincidenceCurveCalc
#define _Included_rpnumerics_CoincidenceCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_CoincidenceCurveCalc
 * Method:    nativeCalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_CoincidenceCurveCalc_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
