/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_DiscriminantLevelCurveCalc */

#ifndef _Included_rpnumerics_DiscriminantLevelCurveCalc
#define _Included_rpnumerics_DiscriminantLevelCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_DiscriminantLevelCurveCalc
 * Method:    calcNative
 * Signature: (D)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_DiscriminantLevelCurveCalc_calcNative
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
