/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_DoubleContactCurveCalc */

#ifndef _Included_rpnumerics_DoubleContactCurveCalc
#define _Included_rpnumerics_DoubleContactCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_DoubleContactCurveCalc
 * Method:    nativeCalc
 * Signature: (II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_DoubleContactCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
