/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_ContactRegionCalc */

#ifndef _Included_rpnumerics_ContactRegionCalc
#define _Included_rpnumerics_ContactRegionCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_ContactRegionCalc
 * Method:    calcNative
 * Signature: (I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ContactRegionCalc_calcNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
