/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_EllipticBoundaryExtensionCalc */

#ifndef _Included_rpnumerics_EllipticBoundaryExtensionCalc
#define _Included_rpnumerics_EllipticBoundaryExtensionCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_EllipticBoundaryExtensionCalc
 * Method:    nativeCalc
 * Signature: ([III)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_EllipticBoundaryExtensionCalc_nativeCalc
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
