/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_IntegralCurveCalc */

#ifndef _Included_rpnumerics_IntegralCurveCalc
#define _Included_rpnumerics_IntegralCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_IntegralCurveCalc
 * Method:    calc
 * Signature: (Lrpnumerics/PhasePoint;II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_IntegralCurveCalc_calc
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
