/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_StationaryPointCalc */

#ifndef _Included_rpnumerics_StationaryPointCalc
#define _Included_rpnumerics_StationaryPointCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_StationaryPointCalc
 * Method:    nativeCalc
 * Signature: (Lwave/util/RealVector;Lwave/util/RealVector;D)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_StationaryPointCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
