/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_HugoniotCurve */

#ifndef _Included_rpnumerics_HugoniotCurve
#define _Included_rpnumerics_HugoniotCurve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_HugoniotCurve
 * Method:    findSigma
 * Signature: (Lrpnumerics/PhasePoint;)D
 */
JNIEXPORT jdouble JNICALL Java_rpnumerics_HugoniotCurve_findSigma
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
