/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_CompositeCalc */

#ifndef _Included_rpnumerics_CompositeCalc
#define _Included_rpnumerics_CompositeCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_CompositeCalc
 * Method:    nativeCalc
 * Signature: (Lrpnumerics/PhasePoint;II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_CompositeCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
