/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_HugoniotContinuationCurveCalc */

#ifndef _Included_rpnumerics_HugoniotContinuationCurveCalc
#define _Included_rpnumerics_HugoniotContinuationCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_HugoniotContinuationCurveCalc
 * Method:    calc
 * Signature: (Lrpnumerics/PhasePoint;I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotContinuationCurveCalc_calc
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
