/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_BoundaryExtensionCurveCalc */

#ifndef _Included_rpnumerics_BoundaryExtensionCurveCalc
#define _Included_rpnumerics_BoundaryExtensionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_BoundaryExtensionCurveCalc
 * Method:    nativeCalc
 * Signature: (IIII)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_BoundaryExtensionCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
