/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_SecondaryBifurcationCurveCalc */

#ifndef _Included_rpnumerics_SecondaryBifurcationCurveCalc
#define _Included_rpnumerics_SecondaryBifurcationCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_SecondaryBifurcationCurveCalc
 * Method:    nativeCalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_SecondaryBifurcationCurveCalc_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
