/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_SubInflectionExtensionCurveCalc */

#ifndef _Included_rpnumerics_SubInflectionExtensionCurveCalc
#define _Included_rpnumerics_SubInflectionExtensionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_SubInflectionExtensionCurveCalc
 * Method:    nativeCalc
 * Signature: (IIIII)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_SubInflectionExtensionCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
