/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_StateInformation */

#ifndef _Included_rpnumerics_StateInformation
#define _Included_rpnumerics_StateInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_StateInformation
 * Method:    getStateInformation
 * Signature: (Lwave/util/RealVector;)Lrpnumerics/RPnStateInfo;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_StateInformation_getStateInformation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
