/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_PointLevelCalc */

#ifndef _Included_rpnumerics_PointLevelCalc
#define _Included_rpnumerics_PointLevelCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_PointLevelCalc
 * Method:    calcNative
 * Signature: (ILwave/util/RealVector;[I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_PointLevelCalc_calcNative
  (JNIEnv *, jobject, jint, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
