/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_WaveCurveCalc */

#ifndef _Included_rpnumerics_WaveCurveCalc
#define _Included_rpnumerics_WaveCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_WaveCurveCalc
 * Method:    nativeCalc
 * Signature: (Lrpnumerics/OrbitPoint;IIII)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveCurveCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
