/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_ExtensionCurveCalc */

#ifndef _Included_rpnumerics_ExtensionCurveCalc
#define _Included_rpnumerics_ExtensionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_ExtensionCurveCalc
 * Method:    nativeCalc
 * Signature: (Ljava/util/List;Ljava/util/List;IIZZ)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ExtensionCurveCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
