/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_HugoniotCurveCalcND */

#ifndef _Included_rpnumerics_HugoniotCurveCalcND
#define _Included_rpnumerics_HugoniotCurveCalcND
#ifdef __cplusplus
extern "C" {
#endif
#undef rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT
#define rpnumerics_HugoniotCurveCalcND_UMINUS_SHIFT 0.01
/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    calc
 * Signature: (Lrpnumerics/PhasePoint;Ljava/lang/String;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotCurveCalcND_calc__Lrpnumerics_PhasePoint_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     rpnumerics_HugoniotCurveCalcND
 * Method:    calc
 * Signature: (Lrpnumerics/PhasePoint;IILwave/util/RealVector;Lwave/util/RealVector;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_HugoniotCurveCalcND_calc__Lrpnumerics_PhasePoint_2IILwave_util_RealVector_2Lwave_util_RealVector_2
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
