/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_ConnectionOrbitCalc */

#ifndef _Included_rpnumerics_ConnectionOrbitCalc
#define _Included_rpnumerics_ConnectionOrbitCalc
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: APPROXIMATION_CHANGE_RELATIVE_MAXIMUM */
/*
 * Class:     rpnumerics_ConnectionOrbitCalc
 * Method:    recalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ConnectionOrbitCalc_recalc
  (JNIEnv *, jobject);

/*
 * Class:     rpnumerics_ConnectionOrbitCalc
 * Method:    calc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_ConnectionOrbitCalc_calc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
