/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_EllipticBoundaryCalc */

#ifndef _Included_rpnumerics_EllipticBoundaryCalc
#define _Included_rpnumerics_EllipticBoundaryCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_EllipticBoundaryCalc
 * Method:    nativeCalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_EllipticBoundaryCalc_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
