/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_OrbitCalc */

#ifndef _Included_rpnumerics_OrbitCalc
#define _Included_rpnumerics_OrbitCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_OrbitCalc
 * Method:    nativeCalc
 * Signature: (Lrpnumerics/OrbitPoint;Lrpnumerics/PhasePoint;DI)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_OrbitCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
