/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_viscousprofile_ViscousProfileData */

#ifndef _Included_rpnumerics_viscousprofile_ViscousProfileData
#define _Included_rpnumerics_viscousprofile_ViscousProfileData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_viscousprofile_ViscousProfileData
 * Method:    updateStationaryList
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_rpnumerics_viscousprofile_ViscousProfileData_updateStationaryList
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
