/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_CoincidenceExtensionCurveCalc */

#ifndef _Included_rpnumerics_CoincidenceExtensionCurveCalc
#define _Included_rpnumerics_CoincidenceExtensionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_CoincidenceExtensionCurveCalc
 * Method:    nativeCalc
 * Signature: (IIIII)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_CoincidenceExtensionCurveCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
