/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_SubInflectionCurveCalc */

#ifndef _Included_rpnumerics_SubInflectionCurveCalc
#define _Included_rpnumerics_SubInflectionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_SubInflectionCurveCalc
 * Method:    nativeCalc
 * Signature: ()Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_SubInflectionCurveCalc_nativeCalc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
