/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_DerivativeDiscriminantLevelCurveCalc */

#ifndef _Included_rpnumerics_DerivativeDiscriminantLevelCurveCalc
#define _Included_rpnumerics_DerivativeDiscriminantLevelCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_DerivativeDiscriminantLevelCurveCalc
 * Method:    calcNative
 * Signature: (I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_DerivativeDiscriminantLevelCurveCalc_calcNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
