/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_EigenValuePointLevelCalc */

#ifndef _Included_rpnumerics_EigenValuePointLevelCalc
#define _Included_rpnumerics_EigenValuePointLevelCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_EigenValuePointLevelCalc
 * Method:    calcNative
 * Signature: (ILwave/util/RealVector;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_EigenValuePointLevelCalc_calcNative
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
