/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_WaveFlow */

#ifndef _Included_rpnumerics_WaveFlow
#define _Included_rpnumerics_WaveFlow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_WaveFlow
 * Method:    flux
 * Signature: (Lwave/util/RealVector;)Lwave/util/RealVector;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveFlow_flux
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rpnumerics_WaveFlow
 * Method:    fluxDeriv
 * Signature: (Lwave/util/RealVector;)Lwave/util/JacobianMatrix;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveFlow_fluxDeriv
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rpnumerics_WaveFlow
 * Method:    fluxDeriv2
 * Signature: (Lwave/util/RealVector;)Lwave/util/HessianMatrix;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveFlow_fluxDeriv2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
