/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_WaveCurve */

#ifndef _Included_rpnumerics_WaveCurve
#define _Included_rpnumerics_WaveCurve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_WaveCurve
 * Method:    nativeDiagramCalc
 * Signature: (II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveCurve_nativeDiagramCalc
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
