/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc */

#ifndef _Included_rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc
#define _Included_rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc
 * Method:    nativeCalc
 * Signature: (II)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc_nativeCalc__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc
 * Method:    nativeCalc
 * Signature: (Ljava/util/List;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_StoneExplicitSecondaryBifurcationCurveCalc_nativeCalc__Ljava_util_List_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
