/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_WaveCurveRRegionsCalc */

#ifndef _Included_rpnumerics_WaveCurveRRegionsCalc
#define _Included_rpnumerics_WaveCurveRRegionsCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_WaveCurveRRegionsCalc
 * Method:    nativeCalc
 * Signature: (I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_WaveCurveRRegionsCalc_nativeCalc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
