/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_CharacteristicsCurveCalc */

#ifndef _Included_rpnumerics_CharacteristicsCurveCalc
#define _Included_rpnumerics_CharacteristicsCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_CharacteristicsCurveCalc
 * Method:    nativeCalc
 * Signature: ([Lrpnumerics/OrbitPoint;I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_CharacteristicsCurveCalc_nativeCalc
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
