/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_RarefactionExtensionCalc */

#ifndef _Included_rpnumerics_RarefactionExtensionCalc
#define _Included_rpnumerics_RarefactionExtensionCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_RarefactionExtensionCalc
 * Method:    nativeCalc
 * Signature: (IILrpnumerics/PhasePoint;IIII)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_RarefactionExtensionCalc_nativeCalc
  (JNIEnv *, jobject, jint, jint, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
