/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_RiemannProfileCalc */

#ifndef _Included_rpnumerics_RiemannProfileCalc
#define _Included_rpnumerics_RiemannProfileCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_RiemannProfileCalc
 * Method:    nativeCalc
 * Signature: (Lwave/util/RealVector;Lwave/util/RealVector;[I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_RiemannProfileCalc_nativeCalc
  (JNIEnv *, jobject, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
