/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_LevelCurveCalc */

#ifndef _Included_rpnumerics_LevelCurveCalc
#define _Included_rpnumerics_LevelCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_LevelCurveCalc
 * Method:    calcNative
 * Signature: (ID[I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_LevelCurveCalc_calcNative
  (JNIEnv *, jobject, jint, jdouble, jintArray);

#ifdef __cplusplus
}
#endif
#endif
