/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_TransitionalLineCalc */

#ifndef _Included_rpnumerics_TransitionalLineCalc
#define _Included_rpnumerics_TransitionalLineCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_TransitionalLineCalc
 * Method:    calc
 * Signature: (Ljava/lang/String;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_TransitionalLineCalc_calc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
