/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpnumerics_InflectionCurveCalc */

#ifndef _Included_rpnumerics_InflectionCurveCalc
#define _Included_rpnumerics_InflectionCurveCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rpnumerics_InflectionCurveCalc
 * Method:    nativeCalc
 * Signature: (I)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_InflectionCurveCalc_nativeCalc__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     rpnumerics_InflectionCurveCalc
 * Method:    nativeCalc
 * Signature: (IIILwave/util/RealVector;Lwave/util/RealVector;)Lrpnumerics/RpSolution;
 */
JNIEXPORT jobject JNICALL Java_rpnumerics_InflectionCurveCalc_nativeCalc__IIILwave_util_RealVector_2Lwave_util_RealVector_2
  (JNIEnv *, jobject, jint, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
