/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wave_multid_model_MultiPolygon */

#ifndef _Included_wave_multid_model_MultiPolygon
#define _Included_wave_multid_model_MultiPolygon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wave_multid_model_MultiPolygon
 * Method:    convexHull
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_wave_multid_model_MultiPolygon_convexHull
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
