
cSRC += 


ccSRC +=  \
	../../../../Equations/Equations.cc \
	../../../../JNI/JNICompositeCalc.cc \
	../../../../JNI/JNIRarefactionCurveCalc.cc \
	../../../../JNI/JNIViscousProfileData.cc \
	../../../../JNI/JNIMultiPolygon.cc \
	../../../../JNI/JNIWaveCurveRRegionsCalc.cc \
	../../../../JNI/JNIIntegralCurveCalc.cc \
	../../../../JNI/JNIEllipticBoundary.cc \
	../../../../JNI/JNIBuckleyLeverettiIInflectionCurveCalc.cc \
	../../../../JNI/JNICoincidenceCurveCalc.cc \
	../../../../JNI/RpNumerics.cc \
	../../../../JNI/JNISecondaryBifurcation.cc \
	../../../../JNI/JNITransitionalLine.cc \
	../../../../JNI/JNIHugoniotCurveCalc.cc \
	../../../../JNI/JNIStateInformation.cc \
	../../../../JNI/JNIShockCurveCalc.cc \
	../../../../JNI/JNIConnectionOrbitCalc.cc \
	../../../../JNI/JNIExtensionCurveCalc.cc \
	../../../../JNI/JNIRPnPluginManager.cc \
	../../../../JNI/JNIWaveCurveCalc.cc \
	../../../../JNI/JNIBoundaryExtensionCalc.cc \
	../../../../JNI/JNIRarefactionExtensionCalc.cc \
	../../../../JNI/JNIPhysicalBondaryCalc.cc \
	../../../../JNI/JNICoincidenceExtensionCurve.cc \
	../../../../JNI/JNIRiemannProfileCalc.cc \
	../../../../JNI/JNIInflectionCurveCalc.cc \
	../../../../JNI/JNIEnvelopeCurve.cc \
	../../../../JNI/JNIEllipticBoundaryExtension.cc \
	../../../../JNI/JNIStationaryPointCalc.cc \
	../../../../JNI/JNIOrbitCalc.cc \
	../../../../JNI/JNIRPnDesktopPlotter.cc \
	../../../../JNI/JNILevelCurveCalc.cc \
	../../../../JNI/JNICharacteristicsCurveCalc.cc \
	../../../../JNI/JNIManifoldOrbitCalc.cc \
	../../../../JNI/JNIWaveCurveSpeedDiagram.cc \
	../../../../JNI/JNIDoubleContact.cc \
	../../../../JNI/JNIHysteresis.cc \
	../../../../JNI/JNIDiscriminantLevelCurveCalc.cc \
	../../../../JNI/JNISubInflectionExtensionCurveCalc.cc \
	../../../../JNI/JNISubInflectionCurveCalc.cc \
	../../../../rpnumerics/RpFunction.cc \
	../../../../rpnumerics/Implicit_Curve.cc \
	../../../../rpnumerics/GridValues.cc \
	../../../../rpnumerics/AccumulationParams.cc \
	../../../../rpnumerics/ShockFlowParams.cc \
	../../../../rpnumerics/WaveState.cc \
	../../../../rpnumerics/DefaultAccumulationFunction.cc \
	../../../../rpnumerics/AccumulationFunction.cc \
	../../../../rpnumerics/RarefactionCalc.cc \
	../../../../rpnumerics/Hugoniot_Curve.cc \
	../../../../rpnumerics/plugin/RPnPluginManager.cc \
	../../../../rpnumerics/plugin/PluginService.cc \
	../../../../rpnumerics/Envelope_Curve.cc \
	../../../../rpnumerics/Elliptic_Boundary.cc \
	../../../../rpnumerics/Hugoniot_Locus.cc \
	../../../../rpnumerics/RpCalculation.cc \
	../../../../rpnumerics/Double_Contact_Function.cc \
	../../../../rpnumerics/physics/SimpleFlux/SimpleFlux.cc \
	../../../../rpnumerics/physics/CompositionalPhysics/Hugoniot_TP.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowViscosity.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowEquationFunctionLevelCurve.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowSubPhysics.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowMobilityLevelCurve.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/Foam/FoamPermeability.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/Foam/FoamSubPhysics.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/Foam/FoamViscosity.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/Foam/FoamFluxFunction.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/Three_Phase_Flow_Explicit_Bifurcation_Curves.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowPermeability.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowMobility.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowPermeabilityLevelCurve.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowAccumulation.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowImplicitHugoniotCurve.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowHugoniotContinuation.cc \
	../../../../rpnumerics/physics/ThreePhaseFlowPhysics/ThreePhaseFlowFluxFunction.cc \
	../../../../rpnumerics/Extension_Curve.cc \
	../../../../rpnumerics/HugoniotSegment.cc \
	../../../../rpnumerics/viscousprofile/StationaryPoint.cc \
	../../../../rpnumerics/characteristics/plotter.cc \
	../../../../rpnumerics/characteristics/curvegen.cc \
	../../../../rpnumerics/characteristics/interpol.cc \
	../../../../rpnumerics/Double_Contact.cc \
	../../../../rpnumerics/RPnCurve.cc \
	../../../../rpnumerics/DefaultAccumulationParams.cc \
	../../../../rpnumerics/EllipticExtension.cc \
	../../../../rpnumerics/Inflection_Curve.cc \
	../../../../rpnumerics/Secondary_Bifurcation.cc \
	../../../../rpnumerics/methods/Secondary_Bifurcations/Explicit_Bifurcation_Curves/Explicit_Bifurcation_Curves.cc \
	../../../../rpnumerics/methods/Viscosity_Matrix/Viscosity_Matrix.cc \
	../../../../rpnumerics/methods/Viscosity_Matrix/ViscosityJetMatrix.cc \
	../../../../rpnumerics/methods/Bisection/Bisection.cc \
	../../../../rpnumerics/methods/TransitionalShock/TransitionalShock.cc \
	../../../../rpnumerics/methods/contour/Contour2x2_Method.cc \
	../../../../rpnumerics/methods/contour/HugoniotFunctionClass.cc \
	../../../../rpnumerics/methods/contour/Contour2p5_Method.cc \
	../../../../rpnumerics/methods/contour/ContourMethod.cc \
	../../../../rpnumerics/methods/contour/HyperCube.cc \
	../../../../rpnumerics/methods/contour/GPU/Contour2x2_Method_GPU.cc \
	../../../../rpnumerics/methods/contour/GPU/Double_Contact_GPU.cc \
	../../../../rpnumerics/methods/contour/ContourMethodPure.cc \
	../../../../rpnumerics/methods/ShockCurve/ClassifyShockCurve.cc \
	../../../../rpnumerics/methods/ShockCurve/ShockCurve.cc \
	../../../../rpnumerics/methods/ReferencePoint.cc \
	../../../../rpnumerics/methods/RarefactionCurve/RarefactionCurve.cc \
	../../../../rpnumerics/methods/Coincidence_Contour/Coincidence_Contour.cc \
	../../../../rpnumerics/methods/Extension/Implicit_Extension_Curve.cc \
	../../../../rpnumerics/methods/Extension/Extension.cc \
	../../../../rpnumerics/methods/HugoniotCurve/ImplicitHugoniotCurve.cc \
	../../../../rpnumerics/methods/HugoniotCurve/HugoniotCurve.cc \
	../../../../rpnumerics/methods/CharacteristicPolynomialLevels/CharacteristicPolynomialLevels.cc \
	../../../../rpnumerics/methods/BifurcationCurve/BifurcationCurve.cc \
	../../../../rpnumerics/methods/CompositeCurve/CompositeCurve.cc \
	../../../../rpnumerics/methods/EquationFunctionLevelCurve/EquationFunctionLevelCurve.cc \
	../../../../rpnumerics/methods/NewRarefactionCurve/NewRarefactionCurve.cc \
	../../../../rpnumerics/methods/HugoniotContinuation/HugoniotContinuation_nDnD/HugoniotContinuation_nDnD.cc \
	../../../../rpnumerics/methods/HugoniotContinuation/HugoniotContinuation2D2D/HugoniotContinuation2D2D.cc \
	../../../../rpnumerics/methods/HugoniotContinuation/HugoniotContinuation.cc \
	../../../../rpnumerics/methods/HugoniotContinuation/HugoniotContinuation_nD_nm1D/HugoniotContinuation_nD_nm1D.cc \
	../../../../rpnumerics/methods/HugoniotContinuation/HugoniotContinuation3D2D/HugoniotContinuation3D2D.cc \
	../../../../rpnumerics/methods/RiemannSolver/RiemannProblem.cc \
	../../../../rpnumerics/methods/WaveCurve/WaveCurveFactory.cc \
	../../../../rpnumerics/methods/WaveCurve/WaveCurve.cc \
	../../../../rpnumerics/Newton_Improvement.cc \
	../../../../rpnumerics/PhasePoint.cc \
	../../../../rpnumerics/Rarefaction.cc \
	../../../../rpnumerics/FluxFunction.cc \
	../../../../rpnumerics/FluxParams.cc \
	../../../../rpnumerics/WavePoint.cc \
	../../../../rpnumerics/ParametricPlot/ParametricPlot.cc \
	../../../../rpnumerics/RpSolution.cc \
	../../../../rpnumerics/Hysteresis.cc \
	../../../../rpnumerics/Curve/Curve.cc \
	../../../../Model/SubPhysics.cc \
	../../../../Model/Physics.cc \
	../../../../Model/TrivialAccumulationFunction.cc \
	../../../../Model/Parameter.cc \
	../../../../JetTester/JetTester2D.cc \
	../../../../JetTester/JetTester.cc \
	../../../../JetTester/JetTester1D.cc \
	../../../../JetTester/TestableJet.cc \
	../../../../wave/multid/Space.cc \
	../../../../wave/multid/Multid.cc \
	../../../../wave/ode/EulerSolver/EulerSolver.cc \
	../../../../wave/ode/LSODE/LSODE.cc \
	../../../../wave/util/RealMatrix2.cc \
	../../../../wave/util/IntArray.cc \
	../../../../wave/util/Line.cc \
	../../../../wave/util/IsoTriang2DBoundary.cc \
	../../../../wave/util/HessianMatrix.cc \
	../../../../wave/util/JetMatrix.cc \
	../../../../wave/util/mathutil.cc \
	../../../../wave/util/bool.cc \
	../../../../wave/util/Boundary.cc \
	../../../../wave/util/JacobianMatrix.cc \
	../../../../wave/util/Utilities.cc \
	../../../../wave/util/RealSegment.cc \
	../../../../wave/util/errorhandler.cc \
	../../../../wave/util/except.cc \
	../../../../wave/util/RealVector.cc \
	../../../../wave/util/eigen.cc \
	../../../../wave/util/RectBoundary.cc


cppSRC +=  \
	../../../../rpnumerics/Eigenvalue_Contour.cpp \
	../../../../rpnumerics/methods/Viscosity_Matrix/DoubleMatrix.cpp \
	../../../../rpnumerics/methods/HugoniotCurve/ColorCurve.cpp \
	../../../../wave/util/PointND.cpp \
	../../../../wave/util/BoxND.cpp \
	../../../../wave/util/alglib/alglib/wsr.cpp \
	../../../../wave/util/alglib/alglib/ssolve.cpp \
	../../../../wave/util/alglib/alglib/jarquebera.cpp \
	../../../../wave/util/alglib/alglib/blas.cpp \
	../../../../wave/util/alglib/alglib/expintegrals.cpp \
	../../../../wave/util/alglib/alglib/pca.cpp \
	../../../../wave/util/alglib/alglib/rotations.cpp \
	../../../../wave/util/alglib/alglib/lda.cpp \
	../../../../wave/util/alglib/alglib/conv.cpp \
	../../../../wave/util/alglib/alglib/fft.cpp \
	../../../../wave/util/alglib/alglib/hblas.cpp \
	../../../../wave/util/alglib/alglib/elliptic.cpp \
	../../../../wave/util/alglib/alglib/spline1d.cpp \
	../../../../wave/util/alglib/alglib/descriptivestatistics.cpp \
	../../../../wave/util/alglib/alglib/spline3.cpp \
	../../../../wave/util/alglib/alglib/trlinsolve.cpp \
	../../../../wave/util/alglib/alglib/mlptrain.cpp \
	../../../../wave/util/alglib/alglib/ratinterpolation.cpp \
	../../../../wave/util/alglib/alglib/apserv.cpp \
	../../../../wave/util/alglib/alglib/mannwhitneyu.cpp \
	../../../../wave/util/alglib/alglib/reflections.cpp \
	../../../../wave/util/alglib/alglib/trfac.cpp \
	../../../../wave/util/alglib/alglib/hqrnd.cpp \
	../../../../wave/util/alglib/alglib/nearestneighbor.cpp \
	../../../../wave/util/alglib/alglib/odesolver.cpp \
	../../../../wave/util/alglib/alglib/spdgevd.cpp \
	../../../../wave/util/alglib/alglib/poissondistr.cpp \
	../../../../wave/util/alglib/alglib/sinverse.cpp \
	../../../../wave/util/alglib/alglib/minlbfgs.cpp \
	../../../../wave/util/alglib/alglib/gammafunc.cpp \
	../../../../wave/util/alglib/alglib/xblas.cpp \
	../../../../wave/util/alglib/alglib/matinv.cpp \
	../../../../wave/util/alglib/alglib/autogk.cpp \
	../../../../wave/util/alglib/alglib/hsschur.cpp \
	../../../../wave/util/alglib/alglib/logit.cpp \
	../../../../wave/util/alglib/alglib/mlpbase.cpp \
	../../../../wave/util/alglib/alglib/correlationtests.cpp \
	../../../../wave/util/alglib/alglib/fht.cpp \
	../../../../wave/util/alglib/alglib/ablas.cpp \
	../../../../wave/util/alglib/alglib/bdss.cpp \
	../../../../wave/util/alglib/alglib/matdet.cpp \
	../../../../wave/util/alglib/alglib/igammaf.cpp \
	../../../../wave/util/alglib/alglib/fresnel.cpp \
	../../../../wave/util/alglib/alglib/airyf.cpp \
	../../../../wave/util/alglib/alglib/densesolver.cpp \
	../../../../wave/util/alglib/alglib/nearunityunit.cpp \
	../../../../wave/util/alglib/alglib/srcond.cpp \
	../../../../wave/util/alglib/alglib/gkq.cpp \
	../../../../wave/util/alglib/alglib/mlpe.cpp \
	../../../../wave/util/alglib/alglib/creflections.cpp \
	../../../../wave/util/alglib/alglib/normaldistr.cpp \
	../../../../wave/util/alglib/alglib/psif.cpp \
	../../../../wave/util/alglib/alglib/gq.cpp \
	../../../../wave/util/alglib/alglib/lsfit.cpp \
	../../../../wave/util/alglib/alglib/chisquaredistr.cpp \
	../../../../wave/util/alglib/alglib/correlation.cpp \
	../../../../wave/util/alglib/alglib/rcond.cpp \
	../../../../wave/util/alglib/alglib/idwint.cpp \
	../../../../wave/util/alglib/alglib/dawson.cpp \
	../../../../wave/util/alglib/alglib/studentttests.cpp \
	../../../../wave/util/alglib/alglib/hermite.cpp \
	../../../../wave/util/alglib/alglib/jacobianelliptic.cpp \
	../../../../wave/util/alglib/alglib/fdistr.cpp \
	../../../../wave/util/alglib/alglib/linreg.cpp \
	../../../../wave/util/alglib/alglib/ibetaf.cpp \
	../../../../wave/util/alglib/alglib/dforest.cpp \
	../../../../wave/util/alglib/alglib/mincg.cpp \
	../../../../wave/util/alglib/alglib/ap.cpp \
	../../../../wave/util/alglib/alglib/stest.cpp \
	../../../../wave/util/alglib/alglib/evd.cpp \
	../../../../wave/util/alglib/alglib/ablasf.cpp \
	../../../../wave/util/alglib/alglib/matgen.cpp \
	../../../../wave/util/alglib/alglib/ftbase.cpp \
	../../../../wave/util/alglib/alglib/kmeans.cpp \
	../../../../wave/util/alglib/alglib/minlm.cpp \
	../../../../wave/util/alglib/alglib/variancetests.cpp \
	../../../../wave/util/alglib/alglib/trigintegrals.cpp \
	../../../../wave/util/alglib/alglib/binomialdistr.cpp \
	../../../../wave/util/alglib/alglib/pspline.cpp \
	../../../../wave/util/alglib/alglib/ratint.cpp \
	../../../../wave/util/alglib/alglib/laguerre.cpp \
	../../../../wave/util/alglib/alglib/sblas.cpp \
	../../../../wave/util/alglib/alglib/bessel.cpp \
	../../../../wave/util/alglib/alglib/ortfac.cpp \
	../../../../wave/util/alglib/alglib/betaf.cpp \
	../../../../wave/util/alglib/alglib/legendre.cpp \
	../../../../wave/util/alglib/alglib/estnorm.cpp \
	../../../../wave/util/alglib/alglib/sdet.cpp \
	../../../../wave/util/alglib/alglib/schur.cpp \
	../../../../wave/util/alglib/alglib/bdsvd.cpp \
	../../../../wave/util/alglib/alglib/tsort.cpp \
	../../../../wave/util/alglib/alglib/ldlt.cpp \
	../../../../wave/util/alglib/alglib/safesolve.cpp \
	../../../../wave/util/alglib/alglib/inverseupdate.cpp \
	../../../../wave/util/alglib/alglib/studenttdistr.cpp \
	../../../../wave/util/alglib/alglib/svd.cpp \
	../../../../wave/util/alglib/alglib/chebyshev.cpp \
	../../../../wave/util/alglib/alglib/ialglib.cpp \
	../../../../wave/util/alglib/alglib/spline2d.cpp \
	../../../../wave/util/alglib/alglib/minasa.cpp \
	../../../../wave/util/alglib/alglib/linmin.cpp \
	../../../../wave/util/alglib/alglib/polint.cpp \
	../../../../wave/util/alglib/alglib/corr.cpp


FSRC +=  \
	../../../../wave/ode/LSODE/lsode3.F \
	../../../../wave/ode/LSODE/lsode2.F \
	../../../../wave/ode/LSODE/lsode.F

